version: '3.9'
services:
  postgres-events:
    image: postgres:15
    container_name: postgres-events
    env_file:
      - ./config/conf.env
    volumes:
      - .:/app
    ports:
      - "5432:5432"