version: '3.9'
services:
  line-provider:
    build: 
      context: .
    ports:
      - "9000:8000"
    env_file:
      - ./config/conf.env
    volumes:
      - .:/app
    container_name: line-provider
    command: /bin/bash -c "alembic upgrade head && uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"